# Site settings
title:       ./Learning
email:       dimanothacker99@gmail.com
author:      Dimas Setya Aji
description: "Just blogging and learn the code."
baseurl:     ""
url:         "http://d3f4lt.github.io"

google_analytics:
animated:           true
show_related_posts: true
show_post_footers:  false
show_social_icons:  true
disqus_shortname: d3f4lt
github_username: D3f4lt
stackoverflow_id:
twitter_username: DImasetyaji
google_plus_id: +DimasSetyaAji
linkedin_username:
bitcoin_url:
paypal_url:
flattr_button:

markdown:     kramdown
redcarpet:
  extensions: ['smart', 'tables', 'with_toc_data']
permalink:    pretty
paginate:     3
sass:
  compressed: true
gems:
  - jekyll-sitemap
